name: API FastPix Build and Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'back/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'back/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and Test with Maven
      run: mvn -B test --file pom.xml

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: back/target/surefire-reports/
